name: Alipay Cloud Devops Codescan
on:
  pull_request:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: codeScan
        uses: layotto/alipay-cloud-devops-codescan@create-temp-branch-on-pr
        with:
          parent_uid: ${{ secrets.ALI_PID }}
          private_key: ${{ secrets.ALI_PK }}

